# Generated by Django 5.1.1 on 2024-10-01 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('arquivo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(default='2020.1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='não há registro', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo_ingresso',
            field=models.CharField(choices=[('2024.2', '2024.2'), ('2024.1', '2024.1'), ('2023.2', '2023.2'), ('2023.1', '2023.1')], default='Não tenho', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_servico', models.CharField(choices=[('aula', 'Aula'), ('reunião', 'Reunião'), ('prova', 'Prova')], max_length=20, null=True)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('turma', 'Trocar de Turma'), ('matricula', 'Declaração de Matrícula'), ('irpf', 'Declaração de Imposto de Renda')], max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
