# Generated by Django 5.1.1 on 2024-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
