# Generated by Django 5.1.1 on 2024-09-24 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_documento_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('turma', 'Trocar de Turma'), ('matricula', 'Declaração de Matrícula'), ('irpf', 'Declaração de Imposto de Renda')], max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('horario_funcionamento_inicio', models.TimeField(default='08:00')),
                ('horario_funcionamento_fim', models.TimeField(default='18:00')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
