# Generated by Django 5.1.1 on 2024-09-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_solicitacao_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='horario_funcionamento_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='horario_funcionamento_inicio',
        ),
    ]
