# Generated by Django 5.1.1 on 2024-09-26 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_servico',
            field=models.CharField(choices=[('aula', 'Aula'), ('reunião', 'Reunião'), ('prova', 'Prova')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
