# Generated by Django 5.1.1 on 2024-09-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_evento_aluno_evento_tipo_servico_and_more'),
        ('usuarios', '0006_remove_solicitacao_horario_funcionamento_fim_and_more'),
    ]

    operations = [
    ]
