# Generated by Django 5.1.1 on 2024-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(default='2020.1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='não há registro', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo_ingresso',
            field=models.CharField(choices=[('2024.2', '2024.2'), ('2024.1', '2024.1'), ('2023.2', '2023.2'), ('2023.1', '2023.1')], default='Não tenho', max_length=20, null=True),
        ),
    ]
