# Generated by Django 5.1.2 on 2024-10-14 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_nota_registrofalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrofalta',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
